/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Contributors: typeof import('./components/Contributors.vue')['default']
    CourseLink: typeof import('./components/CourseLink.vue')['default']
    FeaturesList: typeof import('./components/FeaturesList.vue')['default']
    HomePage: typeof import('./components/HomePage.vue')['default']
    ListItem: typeof import('./components/ListItem.vue')['default']
<<<<<<< HEAD
=======
    NonProjectOption: typeof import('./components/NonProjectOption.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
>>>>>>> e3da066a38b6b4f460d82bc2e00ed450dbe1ac75
  }
}
