// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Contributors: typeof import('./components/Contributors.vue')['default']
    FeaturesList: typeof import('./components/FeaturesList.vue')['default']
    HomePage: typeof import('./components/HomePage.vue')['default']
    ListItem: typeof import('./components/ListItem.vue')['default']
    TeamMember: typeof import('./components/TeamMember.vue')['default']
  }
}

export { }
