/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Contributors: typeof import('./components/Contributors.vue')['default']
    CourseLink: typeof import('./components/CourseLink.vue')['default']
    FeaturesList: typeof import('./components/FeaturesList.vue')['default']
    HomePage: typeof import('./components/HomePage.vue')['default']
    ListItem: typeof import('./components/ListItem.vue')['default']
    NonProjectOption: typeof import('./components/NonProjectOption.vue')['default']
<<<<<<< HEAD
=======
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Version: typeof import('./components/Version.vue')['default']
>>>>>>> e09eb3c4eb5173c7ab4f8135e65e7da00435847a
  }
}
