name: autosync

on:
  schedule:
    - cron: '0 6 * * *' # At 06:00. https://crontab.guru/
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: vuejs-translations/ryu-cho@v1
        with:
          access-token: ${{ secrets.AUTO_SYNC_ACCESS_TOKEN }}
          username: github-actions
          email: "action@github.com"

          upstream-repo: https://github.com/vitest-dev/docs-cn.git
          upstream-repo-branch: sync

          head-repo: https://github.com/vitest-dev/vitest
          head-repo-branch: main
          track-from: da7ce1712fd4d0e4e807ec01ce755581e6892d5b # v4.0.0
          path-starts-with: docs/
          workflow-name: AutoSync

